/* 
 * Employer-Favourites-Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EmployerFavouritesApi.Client.Api;
using EmployerFavouritesApi.Client.Model;
using EmployerFavouritesApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EmployerFavouritesApi.Client.Test
{
    /// <summary>
    ///  Class for testing ApprenticeshipFavourite
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApprenticeshipFavouriteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApprenticeshipFavourite
        //private ApprenticeshipFavourite instance;

        public ApprenticeshipFavouriteTests()
        {
            // TODO uncomment below to create an instance of ApprenticeshipFavourite
            //instance = new ApprenticeshipFavourite();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApprenticeshipFavourite
        /// </summary>
        [Fact]
        public void ApprenticeshipFavouriteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApprenticeshipFavourite
            //Assert.IsInstanceOfType<ApprenticeshipFavourite> (instance, "variable 'instance' is a ApprenticeshipFavourite");
        }


        /// <summary>
        /// Test the property 'ApprenticeshipId'
        /// </summary>
        [Fact]
        public void ApprenticeshipIdTest()
        {
            // TODO unit test for the property 'ApprenticeshipId'
        }
        /// <summary>
        /// Test the property 'Providers'
        /// </summary>
        [Fact]
        public void ProvidersTest()
        {
            // TODO unit test for the property 'Providers'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
