/* 
 * Employer-Favourites-Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EmployerFavouritesApi.Client.Api;
using EmployerFavouritesApi.Client.Model;
using EmployerFavouritesApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EmployerFavouritesApi.Client.Test
{
    /// <summary>
    ///  Class for testing Favourite
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FavouriteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Favourite
        //private Favourite instance;

        public FavouriteTests()
        {
            // TODO uncomment below to create an instance of Favourite
            //instance = new Favourite();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Favourite
        /// </summary>
        [Fact]
        public void FavouriteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Favourite
            //Assert.IsInstanceOfType<Favourite> (instance, "variable 'instance' is a Favourite");
        }


        /// <summary>
        /// Test the property 'ApprenticeshipId'
        /// </summary>
        [Fact]
        public void ApprenticeshipIdTest()
        {
            // TODO unit test for the property 'ApprenticeshipId'
        }
        /// <summary>
        /// Test the property 'Ukprns'
        /// </summary>
        [Fact]
        public void UkprnsTest()
        {
            // TODO unit test for the property 'Ukprns'
        }

    }

}
