/* 
 * Employer-Favourites-Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EmployerFavouritesApi.Client.Api;
using EmployerFavouritesApi.Client.Model;
using EmployerFavouritesApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EmployerFavouritesApi.Client.Test
{
    /// <summary>
    ///  Class for testing Provider
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProviderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Provider
        //private Provider instance;

        public ProviderTests()
        {
            // TODO uncomment below to create an instance of Provider
            //instance = new Provider();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Provider
        /// </summary>
        [Fact]
        public void ProviderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Provider
            //Assert.IsInstanceOfType<Provider> (instance, "variable 'instance' is a Provider");
        }


        /// <summary>
        /// Test the property 'Ukprn'
        /// </summary>
        [Fact]
        public void UkprnTest()
        {
            // TODO unit test for the property 'Ukprn'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
